feat: add support Application Default Credentials for google-cloud-storage
ducktors/turborepo-remote-cache pull request #66
Opened 2022-10-31 19:06 UTC by nakatanakatana

Tihs PR adds setting to use Application Default Credentials for authentication of google-cloud-storage.

reference:

* https://cloud.google.com/docs/authentication/application-default-credentials
* https://googleapis.dev/nodejs/storage/latest/Storage.html#Storage-examples

2022-11-02 10:31 UTC, fox1t approved these changes
Would you mind adding tests for this configuration?

2022-11-02 10:31 UTC, fox1t commented on src/env.ts
> +    GCS_USE_ADC: Type.Optional(Type.String({ default: 'false' })),
```suggestion
    GCS_USE_ADC: Type.Optional(Type.Boolean({ default: false })),
```

2022-11-02 10:31 UTC, fox1t commented on src/plugins/remote-cache/index.ts
> +      useApplicationDefaultCredentials: instance.config.GCS_USE_ADC == 'true',
```suggestion
      useApplicationDefaultCredentials: instance.config.GCS_USE_ADC === true,
```

2022-11-02 10:31 UTC, fox1t requested changes
Please look at suggestions

2022-11-02 13:52 UTC, emalihin commented
Alternatively we could use ADC if no clientEmail || privateKey` are provided?

2022-11-02 17:58 UTC, fox1t commented
> Alternatively we could use ADC if no `clientEmail || privateKey` are provided?

Would you mind elaborating? I am not an expert when it comes to GCP.

2022-11-03 09:24 UTC, emalihin commented
> Would you mind elaborating? I am not an expert when it comes to GCP.

From docs:
> ADC searches for credentials in the following locations:
>    [GOOGLE_APPLICATION_CREDENTIALS environment variable](https://cloud.google.com/docs/authentication/application-default-credentials#GAC)
>    [User credentials set up with the Google Cloud CLI](https://cloud.google.com/docs/authentication/application-default-credentials#personal)
>    [The attached service account, as provided by the metadata server](https://cloud.google.com/docs/authentication/application-default-credentials#attached-sa)

By simply not providing credentials to `Storage()` constructor we instruct it to use one of the above three methods. The 2nd and 3rd scenarios are most common in my experience - SDK knows where to find local credentials, and it will also check the GCP metadata server for the Service Account information (this is used for Workload Identity auth in GKE - the recommended way to authenticate with GCP. Very similar to AWS's `IAM roles for service accounts/IRSA`)

2022-11-03 16:48 UTC, tehKapa commented
@all-contributors add @nakatanakatana for code

2022-11-04 09:49 UTC, fox1t commented
This PR was superseded by https://github.com/ducktors/turborepo-remote-cache/pull/68

2022-11-04 09:49 UTC, closed without merging