fix: #32, #62
ducktors/turborepo-remote-cache pull request #67
Opened 2022-11-02 21:42 UTC by tm1000

This fixes #32 and #62

2022-11-02 22:10 UTC, tm1000 commented
The only issue I've noticed so far is that if I dont set the ENVs I added I get an error about invalid values. So if someone could direct me on how to fix that I'll do it (or I'll investigate later)

2022-11-03 16:14 UTC, fox1t requested changes

2022-11-03 16:14 UTC, fox1t commented on src/plugins/remote-cache/index.ts
> +  const bodyLimit = instance.config.BODY_LIMIT ?? 104857600
Since we have the default on `BODY_LIMIT: Type.Optional(Type.Number({ default: 104857600 }))` we don't need it here.

2022-11-03 16:14 UTC, fox1t commented on src/plugins/remote-cache/index.ts
> +  const bodyLimit = instance.config.BODY_LIMIT ?? 104857600
Since we have the default on `BODY_LIMIT: Type.Optional(Type.Number({ default: 104857600 }))` we don't need it here.

2022-11-03 16:14 UTC, fox1t commented on src/plugins/remote-cache/index.ts
> +      useTmp: instance.config.STORAGE_PATH_USE_TMP_FOLDER ?? true,
Since we have the default on `STORAGE_PATH_USE_TMP_FOLDER: Type.Optional(Type.Boolean({ default: true }))` we don't need it here.

2022-11-03 16:14 UTC, fox1t commented
Thanks for this PR!
> The only issue I've noticed so far is that if I dont set the ENVs I added I get an error about invalid values. So if someone could direct me on how to fix that I'll do it (or I'll investigate later)


I am not sure about the issue. Where do you see these errors? Can you provide the stacktrace?

2022-11-03 16:15 UTC, fox1t commented
Would you mind adding tests for the additions you made?

2022-11-03 16:48 UTC, tehKapa commented
@all-contributors add @tm1000 for code

2022-11-03 18:07 UTC, tm1000 commented
> I am not sure about the issue. Where do you see these errors? Can you provide the stacktrace?

When using docker (I rebuilt until this makes it in your release)

```
Error: env/STORAGE_PATH_USE_TMP_FOLDER must be boolean
    at loadAndValidateEnvironment (/home/app/node/node_modules/env-schema/index.js:93:19)
    at Object.<anonymous> (/home/app/node/src/env.ts:50:29)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/app/node/src/plugins/remote-cache/storage/index.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14) {
  errors: [
    {
      instancePath: '/STORAGE_PATH_USE_TMP_FOLDER',
      schemaPath: '#/properties/STORAGE_PATH_USE_TMP_FOLDER/type',
      keyword: 'type',
      params: { type: 'boolean' },
      message: 'must be boolean'
    }
  ]
```

2022-11-03 18:09 UTC, tm1000 commented on src/plugins/remote-cache/index.ts
> +  const bodyLimit = instance.config.BODY_LIMIT ?? 104857600
The issue here is that bodyLimit is still undefined re typescript.

2022-11-03 18:21 UTC, tm1000 commented
So I just rebuilt the container and I omitted BODY_LIMIT. It's marked as Optional in the env file but still throws this error unless I define it so I must be missing something

```
Error: env/BODY_LIMIT must be number
    at loadAndValidateEnvironment (/home/app/node/node_modules/env-schema/index.js:93:19)
    at Object.<anonymous> (/home/app/node/src/env.ts:50:29)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/app/node/src/plugins/remote-cache/storage/index.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14) {
  errors: [
    {
      instancePath: '/BODY_LIMIT',
      schemaPath: '#/properties/BODY_LIMIT/type',
      keyword: 'type',
      params: { type: 'number' },
      message: 'must be number'
    }
  ]
}
```

2022-11-03 18:43 UTC, fox1t commented
Maybe for some reason it defaults to empty string? 🤔

2022-11-03 18:55 UTC, tm1000 commented
> Maybe for some reason it defaults to empty string? 🤔

That was it. Its because of the remapping happening inside of the Dockerfile. There's no need to set ENVs back to themselves as this is done automatically in docker itself. So when you end up setting booleans to undefined then it becomes a string and then it doesnt validate. I fixed this in [ea614b3](https://github.com/ducktors/turborepo-remote-cache/pull/67/commits/ea614b370bcdf9c62e9bbd88c193693d84ce5054) and rebuilt my container and now it works without the values defined

2022-11-03 19:11 UTC, tm1000 commented
@fox1t I can write some tests if you think the code is good to go now

2022-11-04 07:31 UTC, fox1t commented
I think that now everything seems in place! Waiting for some tests to merge this!

2022-11-04 07:43 UTC, tehKapa approved these changes

2022-11-05 10:24 UTC, merged

2022-11-06 21:42 UTC, tm1000 commented
@fox1t I'm still working on tests if you want them! Sorry for the delay!